"""
😷 Face Mask Detection - GUI Application
==========================================
Usage: python gui_facemask.py
"""

import os
import sys
import threading
import warnings
warnings.filterwarnings('ignore')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tkinter as tk
from tkinter import filedialog, messagebox
import numpy as np
from PIL import Image, ImageTk

# Global variables
model = None

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(SCRIPT_DIR, 'face_mask_classifier.keras')
IMG_SIZE = 128

# Classes (alphabetical order as generated by ImageDataGenerator)
CLASS_NAMES = ['mask_weared_incorrect', 'with_mask', 'without_mask']

# Modern Color Theme
BG_COLOR = "#121212"
CARD_BG = "#1e1e1e"
ACCENT = "#bb86fc"  # Purple accent
TEXT_COLOR = "#ffffff"
TEXT_SEC = "#b3b3b3"
BORDER = "#333333"

# Status colors
COLOR_SAFE = "#03dac6"     # Teal for 'with_mask'
COLOR_WARN = "#ffb300"     # Amber for 'incorrect'
COLOR_DANGER = "#cf6679"   # Red/Pink for 'without'


class FaceMaskApp:
    def __init__(self, root):
        self.root = root
        self.root.title("😷 Face Mask Detector")
        self.root.geometry("550x650")
        self.root.configure(bg=BG_COLOR)
        self.root.resizable(False, False)

        # Center window on screen
        self.root.update_idletasks()
        x = (self.root.winfo_screenwidth() // 2) - 275
        y = (self.root.winfo_screenheight() // 2) - 325
        self.root.geometry(f"550x650+{x}+{y}")

        self.selected_file = None
        self.photo_image = None
        self.model_ready = False

        self.build_ui()
        print("Starting model load...")
        self.root.after(200, self.load_model_async)

    def build_ui(self):
        # Header
        header = tk.Frame(self.root, bg=ACCENT, height=60)
        header.pack(fill='x')
        header.pack_propagate(False)
        tk.Label(header, text="😷 Face Mask Detector",
                 font=("Segoe UI", 16, "bold"), fg="#000000", bg=ACCENT).pack(pady=15)

        # Loading Status
        self.status_var = tk.StringVar(value="⏳ Loading MobileNetV2 model... please wait")
        tk.Label(self.root, textvariable=self.status_var,
                 font=("Segoe UI", 9), fg=TEXT_SEC, bg=BG_COLOR).pack(pady=8)

        # Controls
        btn_frame = tk.Frame(self.root, bg=BG_COLOR)
        btn_frame.pack(pady=5)

        self.browse_btn = tk.Button(btn_frame, text="📸 Select Image",
                                     font=("Segoe UI", 10, "bold"),
                                     bg=CARD_BG, fg=TEXT_COLOR,
                                     activebackground=BORDER, activeforeground=TEXT_COLOR,
                                     relief='flat', padx=15, pady=8,
                                     cursor="hand2", command=self.browse_file)
        self.browse_btn.pack(side='left', padx=10)

        self.predict_btn = tk.Button(btn_frame, text="🔍 Analyze Face",
                                      font=("Segoe UI", 10, "bold"),
                                      bg=ACCENT, fg="#000000",
                                      activebackground="#d0a9f5",
                                      relief='flat', padx=20, pady=8,
                                      cursor="hand2", command=self.do_predict)
        self.predict_btn.pack(side='left', padx=10)

        # Image Preview
        preview_frame = tk.Frame(self.root, bg=CARD_BG, highlightbackground=BORDER, highlightthickness=1)
        preview_frame.pack(padx=30, pady=15, fill='x')

        self.image_label = tk.Label(preview_frame,
                                     text="No image selected\n\nUpload a picture containing a face",
                                     font=("Segoe UI", 10), fg=TEXT_SEC, bg=CARD_BG,
                                     height=12, width=30)
        self.image_label.pack(padx=10, pady=10, expand=True)

        # Result Details
        result_frame = tk.Frame(self.root, bg=BG_COLOR)
        result_frame.pack(padx=30, pady=5, fill='both', expand=True)

        self.result_title = tk.Label(result_frame, text="TEST RESULT",
                                     font=("Segoe UI", 10, "bold"),
                                     fg=TEXT_SEC, bg=BG_COLOR)
        self.result_title.pack(pady=(10, 0))

        self.result_name = tk.Label(result_frame, text="—",
                                     font=("Segoe UI", 24, "bold"),
                                     fg=TEXT_COLOR, bg=BG_COLOR)
        self.result_name.pack(pady=(5, 0))

        self.result_conf = tk.Label(result_frame, text="Select an image to start",
                                     font=("Segoe UI", 12), fg=TEXT_SEC, bg=BG_COLOR)
        self.result_conf.pack(pady=(0, 15))

        # Probability Bars
        self.bars_frame = tk.Frame(result_frame, bg=BG_COLOR)
        self.bars_frame.pack(fill='x', padx=20)

        self.bar_widgets = []
        for cls in CLASS_NAMES:
            row = tk.Frame(self.bars_frame, bg=BG_COLOR)
            row.pack(fill='x', pady=4)

            name = "Mask Worn Incorrectly" if cls == "mask_weared_incorrect" else cls.replace('_', ' ').title()
            
            lbl = tk.Label(row, text=name, font=("Segoe UI", 9),
                          fg=TEXT_COLOR, bg=BG_COLOR, width=18, anchor='w')
            lbl.pack(side='left')

            canvas = tk.Canvas(row, height=12, bg=CARD_BG, highlightthickness=0)
            canvas.pack(side='left', fill='x', expand=True, padx=8)

            pct = tk.Label(row, text="", font=("Segoe UI", 9, "bold"),
                          fg=TEXT_SEC, bg=BG_COLOR, width=6, anchor='e')
            pct.pack(side='right')

            self.bar_widgets.append((lbl, canvas, pct))

    def load_model_async(self):
        threading.Thread(target=self._load_model, daemon=True).start()

    def _load_model(self):
        global model
        try:
            print("Importing tensorflow...")
            from tensorflow.keras.models import load_model as keras_load

            model_path = MODEL_PATH
            if not os.path.exists(model_path):
                h5_path = model_path.replace('.keras', '.h5')
                if os.path.exists(h5_path):
                    model_path = h5_path
                else:
                    msg = f"Model not found in {SCRIPT_DIR}"
                    print(f"ERROR: {msg}")
                    self.root.after(0, lambda: self.status_var.set(f"❌ {msg}"))
                    return

            print(f"Loading model from: {model_path}")
            try:
                model = keras_load(model_path)
            except Exception as load_err:
                print(f"Standard load failed ({load_err}). Attempting fallback architecture rebuild...")
                # Fallback mechanism for MobileNetV2 + Keras 3 mismatch
                from tensorflow.keras.applications import MobileNetV2
                from tensorflow.keras import layers, models
                base_model = MobileNetV2(
                    weights=None, 
                    include_top=False,
                    input_shape=(IMG_SIZE, IMG_SIZE, 3)
                )
                model = models.Sequential([
                    base_model,
                    layers.GlobalAveragePooling2D(),
                    layers.BatchNormalization(),
                    layers.Dropout(0.3),
                    layers.Dense(256, activation='relu'),
                    layers.BatchNormalization(),
                    layers.Dropout(0.3),
                    layers.Dense(3, activation='softmax')
                ])
                model.load_weights(model_path)
                
            print("Model loaded successfully!")
            self.model_ready = True
            self.root.after(0, lambda: self.status_var.set("✅ Ready! Upload a face image."))

        except Exception as e:
            err_msg = f"❌ Error: {str(e)[:60]}"
            print(f"ERROR loading model: {e}")
            self.root.after(0, lambda msg=err_msg: self.status_var.set(msg))

    def browse_file(self):
        path = filedialog.askopenfilename(
            title="Select Face Image",
            filetypes=[("Image Files", "*.jpg *.jpeg *.png *.bmp *.webp")]
        )
        if path:
            self.selected_file = path
            self._show_preview(path)
            fname = os.path.basename(path)
            self.status_var.set(f"✅ Selected: {fname}")

    def _show_preview(self, path):
        try:
            img = Image.open(path).convert('RGB')
            # Resize for preview
            img.thumbnail((250, 250), Image.LANCZOS)
            self.photo_image = ImageTk.PhotoImage(img)
            self.image_label.config(image=self.photo_image, text="", height=0, width=0)
        except Exception as e:
            self.image_label.config(text=f"Cannot preview image", image="", height=12, width=30)

    def do_predict(self):
        if not self.selected_file:
            messagebox.showinfo("No Image", "Please select an image first.")
            return
        if not self.model_ready:
            messagebox.showinfo("Please Wait", "Model is still loading...")
            return

        self.predict_btn.config(state='disabled', text="⏳ Analyzing...")
        self.status_var.set("🔄 Analyzing face...")
        threading.Thread(target=self._predict, daemon=True).start()

    def _predict(self):
        try:
            # 1. Load and preprocess image
            img = Image.open(self.selected_file).convert('RGB')
            img_resized = img.resize((IMG_SIZE, IMG_SIZE))
            
            # Rescale 1/255 as done in ImageDataGenerator
            img_array = np.array(img_resized) / 255.0
            img_array = np.expand_dims(img_array, axis=0)

            print(f"Predicting: {self.selected_file}")
            predictions = model.predict(img_array, verbose=0)
            pred_idx = np.argmax(predictions[0])
            confidence = predictions[0][pred_idx] * 100
            
            raw_class_name = CLASS_NAMES[pred_idx]
            probabilities = predictions[0] * 100

            self.root.after(0, lambda: self._show_result(raw_class_name, confidence, probabilities))

        except Exception as e:
            err_msg = f"❌ Error: {str(e)[:60]}"
            print(f"Prediction error: {e}")
            self.root.after(0, lambda msg=err_msg: self.status_var.set(msg))
            self.root.after(0, lambda: self.predict_btn.config(state='normal', text="🔍 Analyze Face"))

    def _show_result(self, raw_class_name, confidence, probabilities):
        # UI color scheme mapping
        if raw_class_name == 'with_mask':
            display_name = "WITH MASK"
            color = COLOR_SAFE
        elif raw_class_name == 'without_mask':
            display_name = "NO MASK"
            color = COLOR_DANGER
        else:
            display_name = "INCORRECT MASK"
            color = COLOR_WARN

        self.result_name.config(text=display_name, fg=color)
        self.result_conf.config(text=f"Confidence: {confidence:.2f}%")

        # Update bars
        for i, (lbl, canvas, pct) in enumerate(self.bar_widgets):
            prob = probabilities[i]
            
            # Formatted text
            pct.config(text=f"{prob:.1f}%")

            # Determine bar color based on class type
            if CLASS_NAMES[i] == 'with_mask':
                bar_col = COLOR_SAFE
            elif CLASS_NAMES[i] == 'without_mask':
                bar_col = COLOR_DANGER
            else:
                bar_col = COLOR_WARN
                
            # Dim the non-winning bars
            if i != np.argmax(probabilities):
                bar_col = "#555555"

            # Draw bar
            canvas.delete("all")
            canvas.update_idletasks()
            w = canvas.winfo_width()
            if w > 1:
                # Scale from 0 to 100%
                bar_w = max(2, int((prob / 100.0) * w))
                canvas.create_rectangle(0, 0, bar_w, 12, fill=bar_col, outline="")

        self.status_var.set(f"✅ Analysis complete.")
        self.predict_btn.config(state='normal', text="🔍 Analyze Face")


def main():
    if not os.path.exists(MODEL_PATH):
        h5_path = MODEL_PATH.replace('.keras', '.h5')
        if os.path.exists(h5_path):
            pass
        else:
            print(f"ERROR: Model file not found!")
            print(f"  Expected: {MODEL_PATH}")
            return

    root = tk.Tk()
    app = FaceMaskApp(root)
    root.mainloop()


if __name__ == '__main__':
    main()
